name: soma tower parking renewal 9UDS722

on:
  workflow_dispatch: # keeps only manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Playwright and dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run the script
        run: python offstreet_script_9UDS722.py
